######################################################################
# Automatically generated by qmake (3.0) Thu Feb 16 18:26:49 2017
######################################################################

TEMPLATE = app
TARGET = ComboBox
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += MyDlg.h
SOURCES += main.cpp MyDlg.cpp
