######################################################################
# Automatically generated by qmake (3.0) Thu Feb 16 16:19:56 2017
######################################################################

TEMPLATE = app
TARGET = UDPServer
INCLUDEPATH += .

QT += network

# Input
HEADERS += UDPServer.h
SOURCES += main.cpp UDPServer.cpp
