######################################################################
# Automatically generated by qmake (3.0) Thu Feb 16 11:44:36 2017
######################################################################

TEMPLATE = app
TARGET = ProducerConsumer
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += Thread.h
SOURCES += main.cpp Thread.cpp
