######################################################################
# Automatically generated by qmake (3.0) Thu Feb 16 10:25:43 2017
######################################################################

TEMPLATE = app
TARGET = QMLDemo
INCLUDEPATH += .

QT += widgets quick

# Input
SOURCES += main.cpp
