######################################################################
# Automatically generated by qmake (3.0) Thu Feb 16 17:30:15 2017
######################################################################

TEMPLATE = app
TARGET = MediaPlayer
INCLUDEPATH += .

QT += widgets quick 

# Input
SOURCES += main.cpp
