######################################################################
# Automatically generated by qmake (3.0) Thu Feb 16 16:22:56 2017
######################################################################

TEMPLATE = app
TARGET = UDPClient
INCLUDEPATH += .

QT += network

# Input
HEADERS += UDPClient.h
SOURCES += main.cpp UDPClient.cpp
