######################################################################
# Automatically generated by qmake (3.0) Thu Feb 16 14:47:41 2017
######################################################################

TEMPLATE = app
TARGET = TCPClient
INCLUDEPATH += .

QT += network

# Input
HEADERS += TcpClient.h
SOURCES += main.cpp TcpClient.cpp
