######################################################################
# Automatically generated by qmake (3.0) Thu Feb 16 14:32:09 2017
######################################################################

TEMPLATE = app
TARGET = TCPServer
INCLUDEPATH += .

QT += network

# Input
HEADERS += TcpServer.h
SOURCES += main.cpp TcpServer.cpp
