######################################################################
# Automatically generated by qmake (3.0) Thu Feb 16 18:17:27 2017
######################################################################

TEMPLATE = app
TARGET = TabWidget
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += GridDlg.h HBoxDlg.h MyDlg.h VBoxDlg.h
SOURCES += GridDlg.cpp HBoxDlg.cpp main.cpp MyDlg.cpp VBoxDlg.cpp
